name = "VideCraft: Create"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ed57e553a418a98e27939948f37fdfef2e0a3de904427e324652a9dd78852f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
